### ISSUE TITLE
How common is allowing the build to stay red for long periods?

### ISSUE THREAD

**Issue by gustavopinto** [wagnerfns/ci-analysis#2]
Nessa atividade eu preciso que vc descreva: 

- Identifique a distribuição da duração dos builds quebrados. Pra isso vc precisa plotar alguns histograms ou boxplots pra entender a duração. 
- Inicialmente, selecione o terceiro quartil como metrica de builds quebrados que duraram muito tempo.
- Verifique os projetos (por linguagem, por tamanho) que tem builds com duração >= ao da métrica definida.

**Comment by gustavopinto** [comment]
Algum update por aqui? @wagnerfns?

**Comment by wagnerfns** [comment]
Essa parte ainda não atualizei nada.

**Comment by wagnernegrao** [comment]
Essa parte ainda não atualizei nada

**Comment by wagnernegrao** [comment]
Foi realizada a descrição e o 3 quartil teve valor de 2 dias, como esse valor foi verificado para todos projetos, assim se obteve que 73% de 378 projetos(Java)  estão totalizando 276 projetos com build quebrada com esse intervalo de dias. @gustavopinto

**Comment by gustavopinto** [comment]
OK, faça as descrições por tamanho e linguagem. Gere os plots e coloque no artigo.
