### ISSUE TITLE
How common is  running a build with poor test coverage?

### ISSUE THREAD

**Issue by gustavopinto** [wagnerfns/ci-analysis#3]
Aqui eu preciso que vocês:

- Selecionem um pequeno conjunto de projetos Java que usem maven
- Rodem esses projetos manualmente pra identificar como retirar informação de cobertura
- Tentem aumentar a escala dos projetos (10, 25, 50...) e tentar automatizar o processo de geração de cobertura através de scripts. 

Essa atividade deve ser iniciada pelo @wagnerfns  e conduzida em seguida pelo @leonardofurtado.

**Comment by gustavopinto** [comment]
Algum update por aqui? @wagnerfns?

**Comment by wagnernegrao** [comment]
Ainda estou testando a cobertura dos projetos em java @gustavopinto

**Comment by gustavopinto** [comment]
OK, avalie se tem algum(ns) projeto(s) do TravisTorrent que usa o coveralls.io. Se tiver, veja se dar pra usar algum dado de lá.

**Comment by wagnernegrao** [comment]
ok
