### ISSUE TITLE
Tradução do artigo para o Inglês

### ISSUE THREAD

**Issue by gustavopinto** [wagnerfns/ci-analysis#4]
Você pode ir traduzindo os pontos da metodologia. Use o google translator para apoiar essa atividade. Converse com o Leonardo se for preciso, pois ele fez isso recentemente.

**Comment by gustavopinto** [comment]
Algum update por aqui? @wagnerfns?

**Comment by wagnernegrao** [comment]
Sim, atualizei o que vc estava pedindo no overleaf. @gustavopinto
